export default {
  CREATE_CHECKOUT: "CREATE_CHECKOUT",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART: "UPDATE_CART",
  LOAD_CHECKOUT: "LOAD_CHECKOUT",
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  SET_WISHLIST: 'SET_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  DELETE_WISHLIST: 'DELETE_WISHLIST',
  UPDATE_WISHLIST: 'UPDATE_WISHLIST',
}