export default {
  PDP_SELECT_VARIANT: "PDP_SELECT_VARIANT",
  QV_SELECT_VARIANT: "QV_SELECT_VARIANT",
  SET_QUICKVIEW_PRODUCT: "SET_QUICKVIEW_PRODUCT",
  ADD_REVIEW: "ADD_REVIEW",
  SET_REVIEWS: "SET_REVIEWS",
  ERROR: 'ERROR'
};
