export default {
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  SET_WISHLIST: 'SET_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  DELETE_WISHLIST: 'DELETE_WISHLIST',
  UPDATE_WISHLIST: 'UPDATE_WISHLIST'
}