export default {
    TOGGLE_SEARCH: 'TOGGLE_SEARCH',
    TOGGLE_CART: 'TOGGLE_CART',
    TOGGLE_WISHLIST: 'TOGGLE_WISHLIST',
    TOGGLE_PRODUCT_QUICKVIEW: 'TOGGLE_PRODUCT_QUICKVIEW',
    TOGGLE_MOBILE_NAV: 'TOGGLE_MOBILE_NAV'
}
